import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/image-removebg.png'
import AniText from '@/components/AniText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import Hireme from '@/components/Hireme'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from '@/components/TransitionEffect'
// developer-pic-1.png

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout classname='pt - 0'> 
          <div className='flex item-center justify-between w-full'> 
            <div className='w-1/2'>
              <Image src={profilePic} alt="Digital Art" className='w-full h-auto'/>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AniText text="Turning Vision Into Reality With Sktech And Design" className='!text-6xl !text-left'/>
              <p className='my-4 text-base font-medium'>
              As a skilled Digital Artist, I am dedicated to turning ideas into innovative Design. 
Explore my latest projects and articles, showcasing my expertise in Pro Create and Sktech.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href="/dummy.pdf" target='_blank'
                className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark'
                download={true}
                >Resume <LinkArrow className={"w-6 ml-1"}/>
                
                </Link>
                <Link href="mailto:nikhilganorkar0gmail.com" target='_blank'
                className='ml-4 text-lg font-medium capitalize text-dark underline'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        
        <Hireme />
        <div className='absolute right-8 bottom-8 inline-block w-24'> 
          <Image src={lightBulb} alt="Nikhil" className='w-full h-auto' />
        </div>
      </main>
    </>
  )
}
